### PR TITLE
Add RDS Combined CA 

### PR DESCRIPTION
**Pull request by djfurman**
- Add RDS 2019 Certificate Authority. 
- Update Readme documentation. 
- Remove unused import. 
- Add packaging for *.pem certificates for Python PyPI package

### CODE REVIEW

**Comment by djfurman** [comment]
@AbhimanyuHK any feedback on adding the certificates in and getting an update build in? I was considering modifying the connect method to always include them since this is designed for AWS, but didn't want to presume that you wanted to go that way.

**Comment by AbhimanyuHK** [comment]
@djfurman can you provide more information for adding the PEM file. Sorry for the late reply.

**Comment by djfurman** [comment]
No worries! To do an SSL secured connection to an RDS instance, we need to connect with the verify-ca option. This requires us to pass the RDS certificate authority. By packaging the PEM file, we can keep all the AWS requirements together without having to keep public keys in S3 or elsewhere and pull them on start.

**Comment by djfurman** [comment]
Just a quick bump, did I answer your question? Happy to add more context

**Comment by djfurman** [comment]
@AbhimanyuHK Bumping this PR again. Let me know if you have any questions. 

Also It would be great to get builds for Python 3.7, 3.8 and 3.9 published since 3.6 is reaching end of life.

**Comment by AbhimanyuHK** [comment]
thanks @djfurman

**Comment by djfurman** [comment]
You're most welcome @AbhimanyuHK - is this something you'd be open to a PR from me to help build out? I'm happy to assist if you're open to it. 

I'd love love to also add support for:

- arm64 (Graviton)
- x86_64 (Intel)

**Pull request closed without merging**
